bpm: 95.0

voices:
  min: 30
  max: 70

x_gens: 20
children: 25

modFuncs:
  - name: scoreMelodicMotifs
    weight: 1
    weightCC: 1
    params: []
    voices: [true, true, true]
    normalizationFunc: normalizeMinOneToOne
    hasNormalizedScore: false
    splitVoices: false
    scoreRange: [0, null]

  - name: scoreRhythmicMotifs
    weight: 0
    weightCC: 2
    params: []
    voices: [true, true, true]
    normalizationFunc: normalizeMinOneToOne
    hasNormalizedScore: false
    splitVoices: false
    scoreRange: [0, null]

  - name: scoreOverlap
    weight: 0
    weightCC: 3
    params:
      - name: "Target overlap bass"
        range: [0, 8]
        value: 0
        type: int
        cc: 11
      - name: "Target overlap mid"
        range: [0, 8]
        value: 3
        type: int
        cc: 12
      - name: "Target overlap high"
        range: [0, 8]
        value: 0
        type: int
        cc: 13
    voices: [true, true, true]
    normalizationFunc: normalizeMinOneToOne
    hasNormalizedScore: false
    splitVoices: false
    scoreRange: [null, 1]

  - name: scoreTonality
    weight: 2
    weightCC: 4
    params: []
    voices: [true, true, true]
    normalizationFunc: normalizeMinOneToOne
    hasNormalizedScore: true
    splitVoices: false
    scoreRange: [-1, 1]

  - name: scoreSimultaneousIntervals
    weight: 1
    weightCC: 5
    params: []
    voices: [true, true, true]
    normalizationFunc: normalizeMinOneToOne
    hasNormalizedScore: true
    splitVoices: false
    scoreRange: [-1, 1]

  - name: scoreMeasureForChord
    weight: 2
    weightCC: 6
    params: []
    voices: [true, true, true]
    normalizationFunc: normalizeMinOneToOne
    hasNormalizedScore: true
    splitVoices: false
    scoreRange: [-1, 1]

  - name: scoreGridness16th
    weight: 1
    weightCC: 7
    params:
      - name: Optimum
        range: [0, 1]
        value: 0
        type: float
        cc: 14
    voices: [true, true, true]
    normalizationFunc: normalizeMinOneToOne
    hasNormalizedScore: true
    splitVoices: false
    scoreRange: [-1, 1]

  - name: scoreNoteCount
    weight: 1
    weightCC: 8
    params:
      - name: "Q Note count"
        range: [0, 160]
        value: 16
        type: int
        cc: 15
    voices: [true, true, true]
    normalizationFunc: normalizeMinOneToOne
    hasNormalizedScore: false
    splitVoices: false
    scoreRange: [null, 0]

  - name: scoreNoteDiversity
    weight: 0
    weightCC: 9
    params:
      - name: "Target diversity"
        range: [0, 1]
        value: 1
        type: float
        cc: 16
      - name: "Note length preference"
        range: [0, 1]
        value: 0.5
        type: float
        cc: 17
    voices: [true, true, true]
    normalizationFunc: normalizeMinOneToOne
    hasNormalizedScore: true
    splitVoices: false
    scoreRange: [-1, 1]

  - name: scoreGrowthDensity
    weight: 0
    weightCC: 10
    params:
      - name: "Target density bass"
        range: [0, 8]
        value: 0.1
        type: float
        cc: 18
      - name: "Target density mid"
        range: [0, 8]
        value: 0.1
        type: float
        cc: 19
      - name: "Target density high"
        range: [0, 8]
        value: 0.1
        type: float
        cc: 20
    voices: [true, true, true]
    normalizationFunc: normalizeMinOneToOne
    hasNormalizedScore: false
    splitVoices: false
    scoreRange: [null, 0]
